project:
  type: website
  output-dir: docs

website:
  title: "Jack T. Rametta"
  open-graph: true
  twitter-card: 
    site: "@jtrametta"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.qmd
      - research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

