project:
  type: website
  output-dir: docs

website:
  title: "Jack T. Rametta"
  open-graph: true
  twitter-card: 
    site: "@jtrametta"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.qmd
      - research.qmd
    right:
        - icon: LinkedIn
          href: https://www.linkedin.com/in/jack-rametta-b0546779
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto  # re-render only when source changes
# 
editor: visual

