---
title: "Jack T. Rametta"
editor: visual
---

Hello there! I'm a Postdoctoral Fellow at the Ronald Reagan Presidential Foundation and Institute in Washington D.C. having recently completed a PhD in [Political Science](https://ps.ucdavis.edu/) at the [University of California, Davis](https://www.ucdavis.edu/) with subfields in methods and American politics.

In my research, I employ causally oriented machine learning methods to study American political institutions, political behavior, and public policy. My substantive research agenda focuses on Congressional capacity, oversight, and policymaking. Methodologically, I am interested in the development and application of new methods, as well as accompanying software tools, for difficult social science problems. I have several projects in-progress in this vein with co-authors, and recently taught a graduate-level topical workshop on [causal machine learning](https://samjfuller.com/content/ICPSR_Causal_Machine_Learning_Syllabus_2025.pdf) methods at the Inter-university Consortium for Political & Social Research (ICPSR) at the University of Michigan.

Before graduate school, I was an economic policy research analyst at the [Bipartisan Policy Center](https://bipartisanpolicy.org/). At BPC, I contributed to research on the [federal budget](https://www.pgpf.org/sites/default/files/PGPF-2019-Solutions-Initiative.pdf), [debt limit](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/Debt-Limit-Analysis-Everything-You-Need-to-Know-March-2019.pdf), [Social Security and Medicare financing](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/A-Guide-to-the-2018-Social-Security-and-Medicare-Trustees-Reports.pdf), and [defense personnel reform](https://www.heritage.org/sites/default/files/2018-09/2019_IndexOfUSMilitaryStrength_CHAPTERS_MISZTAL-RAMETTA.pdf).
