---
title: CV
format:
  quarto-cv-pdf: default
author: Jack T. Rametta 
date: last-modified
address: "566 Kerr Hall · 200 California Avenue · Davis CA 95816"
email: jtrametta@ucdavis.edu
fontsize: 11pt
github: CetiAlphaFive 
orcid: 0000-0002-9841-146X 
web: jackrametta.com
fontawesome: yes
nocite: '@*'
bibliography_peer: peer_bib.bib
bibliography_other: other_bib.bib
csl: apa-cv.csl
---

## Education

-   **Ph.D. in Political Science**, The University of California Davis  \hfill 2019 - 2025 (Expected)

-   Dissertation: *The Downfall of the Legislative State: Congressional Capacity before and after the Republican Revolution*

-   Fields: American Politics and Methodology 

-   **B.A. Economics and Political Science**, The George Washington University  \hfill 2013 - 2016

-   Special Honors in Political Science & American Political Science Honors Society

## Research Interests 

-   *Substantive:* American political institutions, Congressional policymaking & oversight capacity, legislative support agencies, political behavior, ideology and public policy    

-   *Methods:* causal inference and causal machine learning, Monte Carlo methods, predictive modeling, design-based inference, experiments, game theory, text analysis 

## Book Project

-   [Advanced Machine Learning for Experiments in the Social Sciences](https://osf.io/tc8gf/?view_only=b0931348167844c1a15026f00537fb58) (with Christopher D. Hare and Sam Fuller)

-   *Advance Contract, Cambridge Elements: Experimental Political Science. Expected 2024-2025.*

## Research under Review

-   [Did the Republican Revolution Hamstring Congressional Oversight? Evidence from 55,000 GAO Reports](https://osf.io/prqd9/). *Under Review. Presented at MPSA 2024.* 

-   [Affect, Not Ideology?: The Heterogeneous Effects of Political Cues on Policy Support](https://osf.io/preprints/osf/4k38a) (with Nicolás de la Cerda and Sam Fuller). *Revise and Resubmit, Political Behavior. Presented at WPSA 2023.* 

-   [The Balance Permutation Test: A Machine Learning Replacement for Balance Tables](https://osf.io/xcwt9)(with Sam Fuller). *Under Review. Presented at UC Davis Political Science Research Workshop and ICPSR 2024.* 

## Selected Research in Preparation

-   Causal Forest and Double Machine Learning for Political Science (with Sam Fuller). *A version of this project was presented at MPSA 2023.*

-   [The Dangers of Calculating Conditional Effects: A Reevaluation of Barber and Pope (2019)](https://osf.io/preprints/osf/hwzsu) (with Sam Fuller). *A version of this project was presented at MPSA 2024.*

-   How Robust are Subgroup Analyses in Political Science? Insights from Dozens of Replications (with 
Giulia Venturini, Richard L. Kornrumpf, and Sam Fuller)

-   Why Play by the Rules? Legislative Delegation to Scorekeepers in the Context of Electoral Competition

## Teaching

Instructor(s) of record listed in the parentheses where applicable.

**Graduate Courses**

Inter-university Consortium for Political and Social Research at the University of Michigan

-   ICPSR 2022-2024: Machine Learning for Social Sciences (Summer: Christopher D. Hare)

The University of California, Davis

-   POL 213: Quantitative Analysis in Politics Science II (MLE) (S: 2022, Lauren Peritz)

-   POL 212: Quantitative Analysis in Political Science I (OLS) (W: 2022, Christopher D. Hare)

-   POL 211: Research Methods: Probability, Statistics, Design (F: 2021, Adrienne Hosek)

**Undergraduate Courses**

-   POL 109: Public Policy and the Governmental Process (S: 2024)

-   POL 051: The Scientific Study of Politics (Research Methods in R) (F/W: 2022-2024, Juan Tellez, McCage Griffiths, Christopher D. Hare)

-   POL 001: Introduction to American Politics Spring 2023 (S: 2021 & 2023, Ben Highton & Scott MacKenzie)

-   POL 114: Quantitative Analysis of Political Data (Research Methods in STATA) (W: 2021, Ben Highton)

-   POL 110: The Strategy of Politics (Game Theory) (F: 2020, Ryan Hübert)

-   POL 147B: British Politics (S: 2020, James F. Adams)

-   POL 012A: Politics and Sports (W: 2020, Ethan Scheiner)

## Software

[**MLbalance:**](https://github.com/CetiAlphaFive/MLbalance) Implements a machine learning balance test, the balance permutation test, for experimental data. This test is designed to detect failures of random assignment or covariate imbalance using boosted random forests and permutation inference. Associated working paper is Rametta and Fuller (2024).

[**MLCause:**](https://github.com/MLCause) A package family in development for the application of machine learning to causal inference. Packages associated with the Cambridge Elements contract as well as other workings papers.

[**gao:**](https://github.com/CetiAlphaFive/gao) A package that scrapes all publicly available Government Accountability Office published materials and returns both the original PDF/.html files as well as a cleaned dataset that extracts information from the pages. Associated working paper is Rametta (2024).

## Association Meetings

-   Midwest Political Science Association Annual Meeting \hfill 2024

-   Midwest Political Science Association Annual Meeting \hfill 2023

-   Western Political Science Association Annual Meeting \hfill 2023

## Graduate Student Researcher Experience

-   Professor Ryan Hübert. Formal Model of Prosecutors and Discrimination. 2021

-   Professor Ryan Hübert. Political Appointments and Outcomes in Federal District Courts. 2020

## Selected Policy Writing

Prior to graduate school, I worked in the public policy space. Over several years as a policy analyst, I (co)authored work on the federal budget, social insurance, public finance, and the federal debt limit among other topics. Some of these publications are listed below.

-   ["Putting America Back On Track: A Bipartisan Approach To Fiscal Policy Solutions"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/09/PGPF-Bipartisan-Policy-Center-Solutions-Initiative-2019-Report.pdf) (with Bill Hoagland, Shai Akabas, Jason Fichtner, and Tim Shaw) 2019. Peter G. Peterson Institute.

-   ["Debt Limit Analysis: Everything You Need to Know in 30 Slides"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/07/Debt-Limit-Analysis-Everything-You-Need-to-Know-in-30-Slides.pdf) (with Shai Akabas and Kody Carmody) 2019. Bipartisan Policy Center.

-   ["Personnel Reform Lives, But Don't Call It 'Force Of The Future'"](https://warontherocks.com/2018/08/personnel-reform-lives-but-dont-call-it-force-of-the-future/) (with Blaise Misztal and Mary Farrell) 2018. War on the Rocks.

-   ["Supplying the Manpower America's National Security Strategy Demands"](https://www.heritage.org/sites/default/files/2018-09/2019_IndexOfUSMilitaryStrength_CHAPTERS_MISZTAL-RAMETTA.pdf) (with Blaise Misztal) 2019. U.S. Index of Military Strength Topical Essay.

-   ["Chartbook: What is the Long-Term Fiscal Outlook for the United States?"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/What-is-the-Long-Term-Fiscal-Outlook-for-the-United-States.pdf) 2018. The Bipartisan Policy Center.

-   ["A Guide to the 2018 Social Security and Medicare Trustees' Reports"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/A-Guide-to-the-2018-Social-Security-and-Medicare-Trustees-Reports.pdf) (BPC staff author with Tim Shaw, lead authors Charles P. Blahous III and Robert D. Reischauer) 2018. Bipartisan Policy Center.

-   ["A Preview of the 2018 Social Security and Medicare Trustees' Reports"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/Preview-2018-Trustees-Report.pdf) (BPC staff author with Tim Shaw, lead authors Charles P. Blahous III and Robert D. Reischauer) 2018. Bipartisan Policy Center.

-   ["A Guide to the 2017 Social Security and Medicare Trustees' Reports"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/BPC-Economy-A-Guide-to-the-2017-Social-Security-and-Medicare-Trustees-Reports.pdf) (BPC staff author with G. William Hoagland, Shai Akabas, and Tim Shaw, lead authors Charles P. Blahous III and Robert D. Reischauer) 2017. Bipartisan Policy Center.

-   ["2017 Debt Limit Analysis"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2021/07/Debt-Limit-Daily-Presenation-8.23.17.pdf) (with Shai Akabas and Tim Shaw) 2017. Bipartisan Policy Center.

-   ["Building a F.A.S.T. Force: A Flexible Personnel System for a Modern Military. Recommendations from the Task Force on Defense Personnel"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/BPC-Defense-Building-A-FAST-Force.pdf) (contributor) 2017. Bipartisan Policy Center.

-   ["Defense Personnel Systems: The Hidden Threat to a High-Performance Force"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/BPC-Defense-Personnel-Systems.pdf) (contributor) 2017. Bipartisan Policy Center.

-   ["The Building Blocks of a Ready Military: People, Funding, Tempo"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/BPC-Defense-Military-Readiness.pdf) (staff author with Lisel Loy, Steve Bell, Blaise Misztal et al., lead authors Leon Panetta, Jim Jones, Kathy Roth-Douquet, and Jim Talent) 2017. Bipartisan Policy Center.

-   ["The Military Compensation Conundrum: Rising Costs, Declining Budgets, and a Stressed Force Caught in the Middle"](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/BPC-Defense-Personnel-Compensation.pdf) (staff author with Lisel Loy, Steve Bell, Blaise Misztal et al, lead authors Leon Panetta, Jim Jones, Kathy Roth-Douquet, and Jim Talent) 2017. Bipartisan Policy Center.

-   ["Chartbook: Social Security & Medicare Explained: Top 10 Questions & Answers."](https://bipartisanpolicy.org/download/?file=/wp-content/uploads/2019/03/Social-Security-and-Medicare-Explained-2019.pdf) (Lead author/designer with Kody Carmody) 2019. Bipartisan Policy Center.

-   ["When Will Federal Deficits Hit \$1 Trillion Next? Probably Sooner than Expected"](https://bipartisanpolicy.org/blog/when-will-federal-deficits-hit-1-trillion-next/) (with Steve Bell and Tim Shaw) 2017. Bipartisan Policy Center. [^1]

-   ["Harvey Raises Stakes on Debt Limit Debate"](https://bipartisanpolicy.org/blog/harvey-raises-stakes-on-debt-limit-debate/) (with Shai Akabas and Tim Shaw) 2017. Bipartisan Policy Center.

-   ["The Financial Future of Social Security and Medicare"](https://bipartisanpolicy.org/blog/the-financial-future-of-social-security-and-medicare/) (with Tim Shaw) 2017. Bipartisan Policy Center.

## Other Skills

Computing: `R`, `python`, `STATA`, Mathematica, \LaTeX, cluster computing    

## References

-   **Ryan Hübert**, Associate Professor of Computational Social Science, Department of Methodology, London School of Economics and Political Science

-   **Christopher D. Hare**, Associate Professor of Political Science, University of California, Davis

-   **Erik J. Engstrom**, Professor of Political Science, University of California, Davis

[^1]: For what it's worth, we were [right about this](https://www.cbo.gov/publication/60039#:~:text=The%20Budget%20Outlook-,Deficits,to%20%242.8%20trillion%20by%202034).  



